apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: relase=promotions-manager,env=test
    service.beta.kubernetes.io/aws-load-balancer-name: "promotions-manager"
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: {{ .Release.Name }}
    {{- include "promotions-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      # nodePort: 30000
  selector:
    app: {{ .Release.Name }}
    {{- include "promotions-manager.selectorLabels" . | nindent 4 }}
